stages:
  - name: Publish flask image
    steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}
  - name: deploy ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH} environment
    steps:
    - applyYamlConfig:
        path: ./k8s-yaml/flask-deployment.yaml
    - applyYamlConfig:
        path: ./k8s-yaml/flask-service.yaml

